language: haskell

env:
 - GHCVER=7.8.3
 - GHCVER=7.8.4
 - GHCVER=head

# Note: the distinction between `before_install` and `install` is not
#       important.
before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get -y install linux-headers-generic
 - sudo apt-get install cabal-install-1.20 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.20 update
 - cabal-1.20 install --only-dependencies

# Here starts the actual work to be performed for the package under
# test; any command which exits with a non-zero exit code causes the
# build to fail.
script:
 # -v2 provides useful information for debugging
 - cabal-1.20 configure -v2

 # this builds all libraries and executables
 # (including tests/benchmarks)
 - cabal-1.20 build

 - cabal-1.20 check

 # tests that a source-distribution can be generated
 - cabal-1.20 sdist

 # check that the generated source-distribution can be built & installed
 - export SRC_TGZ=$(cabal-1.20 info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal-1.18 install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
